import { type NextPage } from "next";
import Head from "next/head";
import { HiSpeakerphone } from 'react-icons/hi';
import { SiConvertio } from 'react-icons/si';
import { FaTeamspeak } from 'react-icons/fa';

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Text To Speech App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-2xl font-extrabold leading-normal text-gray-700 md:text-[2rem]">
          Text-<span className="text-purple-300">Speech</span>-App
        </h1>
        <form>
          <div className="mb-4 w-full bg-gray-50 rounded-lg border border-gray-200 dark:bg-gray-700 dark:border-gray-600">
              <div className="py-2 px-4 bg-white rounded-b-lg dark:bg-gray-800">
                  <textarea id="editor" className="block px-4 w-full text-sm text-gray-800 bg-white border-0 dark:bg-gray-800 focus:ring-0 dark:text-white dark:placeholder-gray-400" placeholder="Write to convert to speach..." required></textarea>
              </div>
              <div className="flex justify-between items-center py-2 px-3 border-b dark:border-gray-600">
                  <div className="flex flex-wrap items-center divide-gray-200 sm:divide-x dark:divide-gray-600">
                      <div className="flex items-center space-x-1">
                          <button type="button" className="p-2 text-gray-500 rounded cursor-pointer hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600">
                              <HiSpeakerphone />
                              <span className="sr-only">Attach file</span>
                          </button>
                      </div>
                      <div className="flex items-center space-x-1">
                          <button type="button" className="p-2 text-gray-500 rounded cursor-pointer hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600">
                              <SiConvertio />
                              <span className="sr-only">Convert</span>
                          </button>
                      </div>
                      <div className="flex items-center space-x-1">
                          <button type="button" className="p-2 text-gray-500 rounded cursor-pointer hover:text-gray-900 hover:bg-gray-100 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600">
                              <FaTeamspeak />
                              <span className="sr-only">Convert</span>
                          </button>
                      </div>
                  </div>
              </div>
              <div className="py-2 px-4 bg-white rounded-b-lg dark:bg-gray-800">
                  <h4 className="uppercase leading-normal text-gray-700 md:text-1 font-bold">Converted ssmlText:</h4>
                  <div>Data</div>
              </div>
          </div>
        </form>
      </main>
    </>
  );
};

export default Home;
